version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: charitypay-postgres-dev
    environment:
      POSTGRES_DB: charitypay_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dev_password_123
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - charitypay-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d charitypay_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache (for future use)
  redis:
    image: redis:7-alpine
    container_name: charitypay-redis-dev
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - charitypay-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  # CharityPay API
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: charitypay-api-dev
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=charitypay_dev;Username=postgres;Password=dev_password_123
      - JwtSettings__SecretKey=dev_super_secret_key_minimum_32_characters_long_for_security
      - FiservSettings__BaseUrl=https://cert.api.fiservapps.com
      - FiservSettings__ApiKey=dev_api_key
      - FiservSettings__ApiSecret=dev_api_secret
      - FiservSettings__StoreId=dev_store_id
      - RedisSettings__ConnectionString=redis:6379
    ports:
      - "5000:80"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - charitypay-network
    volumes:
      - ./src:/app/src:ro
      - ./uploads:/app/uploads
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend (React + Vite)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: charitypay-frontend-dev
    environment:
      - NODE_ENV=development
      - VITE_API_BASE_URL=http://localhost:5000/api/v1
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src:ro
      - ./frontend/public:/app/public:ro
    networks:
      - charitypay-network
    depends_on:
      - api

  # Adminer (Database Management UI)
  adminer:
    image: adminer:4.8.1
    container_name: charitypay-adminer-dev
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    networks:
      - charitypay-network
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  charitypay-network:
    driver: bridge